name: unnoticeable
favicon: null
layout_spectrum: 0.9844070000108331
typography_spectrum: 0.06415877025574446
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8583567410241812
  lightness: 0.11612186301499605
  saturation: 0.8686592767480761
  rhythmicContrast: 0.8336999819148332
purpose: []
