name: unnoticeable
favicon: null
layout_spectrum: 1
typography_spectrum: 0.26305
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffae8'
    - '#08090e'
    - '#9e906d'
    - '#5a5340'
    - '#d6a88e'
  brandStrength: 0.8583567410241812
  lightness: 0.11612186301499605
  saturation: 0.8686592767480761
  rhythmicContrast: 0.8336999819148332
purpose: []
